### PR TITLE
nsntrace: give network namespace a name

### PR DESCRIPTION
**Pull request by jonasdn**
This will make it show up when doing:
  $ ip netns list

And allows us to do more tricks going forward.

### CODE REVIEW

**Comment by pabs3** [comment]
Not sure why this one was closed.

**Comment by pabs3** [comment]
This PR seems like a good idea to me, but I would suggest a couple of changes...

According to the `ip-netns(8)` manual page, the path should be `/run/netns/NAME` instead of `/var/run/netns/NAME`.

When two instances of nsntrace are running at the same time, their namespaces will be the same. Should we differentiate by using nsntrace-$PID instead?

**Review by pabs3 — CHANGES_REQUESTED** [review]
According to the ip-netns(8) manual page, the path should be /run/netns/NAME instead of /var/run/netns/NAME.

When two instances of nsntrace are running at the same time, their namespaces will be the same. Should we differentiate by using nsntrace-$PID instead?

**Comment by jonasdn** [comment]
> According to the ip-netns(8) manual page, the path should be /run/netns/NAME instead of /var/run/netns/NAME.
> 
> 
> 
> When two instances of nsntrace are running at the same time, their namespaces will be the same. Should we differentiate by using nsntrace-$PID instead?

Thanks for review!

Yes, that seems like a nice approach! And well spotted with /run vs /var/run!

**Comment by jonasdn** [comment]
> Not sure why this one was closed.

I thought it was needed to do namespaced nameservers, but it is strictly not. But can still be useful!

**Comment by jonasdn** [comment]
I have updated the commit to use `/run` as path and use `nsntrace-$PID` as name.

**Comment by pabs3** [comment]
Looks good to be committed now.

BTW: typo in the new commit message: alloe

**Comment by jonasdn** [comment]
> Looks good to be committed now.
> 
> BTW: typo in the new commit message: alloe

Fixed!

**Pull request merged**
